#!/usr/bin/env python3
"""Generate stable failure schema, TypeScript and documentation from error-catalog.json."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
CATALOG=ROOT/'contracts'/'error-catalog.json'

def artifacts():
    c=json.loads(CATALOG.read_text(encoding='utf-8')); errors=c['errors']; codes=[x['code'] for x in errors]
    schema={
      '$schema':'https://json-schema.org/draft/2020-12/schema','$id':'military-failure.schema.json','title':'Stable dsh-military Failure','type':'object','additionalProperties':False,
      'required':['code','message','retryable'],'properties':{
       'code':{'enum':codes},'message':{'type':'string','minLength':1,'maxLength':12000},'retryable':{'type':'boolean'},'details':{'type':'object','additionalProperties':True},
      },
    }
    ts=['/* AUTO-GENERATED by scripts/generate_error_artifacts.py. DO NOT EDIT. */','export const militaryErrorCodes = [']
    ts += [f"  {json.dumps(code)}," for code in codes]
    ts += ['] as const','export type MilitaryErrorCode = typeof militaryErrorCodes[number]','',"export type MilitaryErrorCategory = "+' | '.join(json.dumps(x) for x in sorted({e['category'] for e in errors})),'','export interface MilitaryFailure {','  readonly code: MilitaryErrorCode','  readonly message: string','  readonly retryable: boolean','  readonly details?: Readonly<Record<string, unknown>>','}','','export interface MilitaryErrorMetadata {','  readonly category: MilitaryErrorCategory','  readonly defaultRetryable: boolean','  readonly summary: string','  readonly recovery: string','}','','export const militaryErrorMetadata: Readonly<Record<MilitaryErrorCode, MilitaryErrorMetadata>> = {']
    for e in errors:
        ts += [f"  {json.dumps(e['code'])}: {{",f"    category: {json.dumps(e['category'])},",f"    defaultRetryable: {str(e['defaultRetryable']).lower()},",f"    summary: {json.dumps(e['summary'],ensure_ascii=False)},",f"    recovery: {json.dumps(e['recovery'],ensure_ascii=False)},",'  },']
    ts += ['}','']
    md=['# 错误目录（生成）','', '> 真源：`contracts/error-catalog.json`。','', '| Code | 分类 | 默认可重试 | 恢复 |','|---|---|---:|---|']
    for e in errors:
        md.append(f"| `{e['code']}` | `{e['category']}` | {'是' if e['defaultRetryable'] else '否'} | {e['recovery'].replace('|','\\|')} |")
    md.append('')
    example={'code':'BUDGET_RESERVATION_REQUIRED','message':'A resource reservation is required before the Worker can start.','retryable':True,'details':{'scopeType':'TASK','scopeId':'task-react-filter','policyId':'budget-worker-standard'}}
    return {
      ROOT/'schemas'/'military-failure.schema.json':json.dumps(schema,ensure_ascii=False,indent=2)+'\n',
      ROOT/'reference'/'types'/'generated-error-catalog.ts':'\n'.join(ts),
      ROOT/'contracts'/'ERROR-CATALOG.md':'\n'.join(md),
      ROOT/'examples'/'contracts'/'military-failure.example.json':json.dumps(example,ensure_ascii=False,indent=2)+'\n',
    }

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args(); stale=[]
    for path,content in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8')!=content: stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding='utf-8'); print(f'Wrote {path.relative_to(ROOT)}')
    if stale:
        print('Stale generated error artifacts:'); [print('- '+x) for x in stale]; return 1
    return 0
if __name__=='__main__': raise SystemExit(main())
