/* AUTO-GENERATED by scripts/generate_contract_artifacts.py. DO NOT EDIT. */
import type {
  AgentIdentity,
  ArtifactRef,
  DataClassification,
  EvidenceRef,
  IsoDateTime,
  ReasoningEffort,
  TacticalSkillRef,
} from './domain.js'

export type MilitarySessionBoundPayload = {
  readonly "bindingRef": string
  readonly "presetId": "military"
  readonly "presetGeneration": string
  readonly "capabilityFingerprint": string
  readonly "rootSessionId": string
}

export type MilitarySessionQuarantinedPayload = {
  readonly "sessionId": string
  readonly "reasonCode": "GENERATION_MISSING" | "GENERATION_INCOMPATIBLE" | "CAPABILITY_MISMATCH" | "MIGRATION_REQUIRED"
  readonly "expectedGeneration": string
  readonly "actualGeneration": string
  readonly "migrationOrderId"?: string
}

export type PresetGenerationResumeCheckedPayload = {
  readonly "sessionId": string
  readonly "requestedGeneration": string
  readonly "activeGeneration": string
  readonly "disposition": "MATCHED" | "ARCHIVE_REBOUND" | "QUARANTINED"
}

export type PresetMigrationCompletedPayload = {
  readonly "migrationOrderId": string
  readonly "sessionId": string
  readonly "fromGeneration": string
  readonly "toGeneration": string
  readonly "disposition": "REBIND_ARCHIVE" | "EXPORT_IMPORT" | "NEW_PRESET_ID"
  readonly "newSessionId"?: string
}

export type MissionStartedPayload = {
  readonly "title": string
  readonly "rootSessionId": string
  readonly "authorityContextRef": string
}

export type MissionCommandAcceptedPayload = {
  readonly "commandId": string
  readonly "idempotencyKey": string
  readonly "commandType": string
  readonly "payloadSha256": string
  readonly "actorAuthorityRef": string
  readonly "taskId"?: string
  readonly "taskVersion"?: number
}

export type MissionIntentRatifiedPayload = {
  readonly "missionIntentRef": string
  readonly "approvedBy": string
  readonly "decisionReceiptRef": string
}

export type DirectionRatifiedPayload = {
  readonly "directionId": string
  readonly "directionPlanRef": string
  readonly "staffCouncilRef": string
}

export type WaveOpenedPayload = {
  readonly "directionId": string
  readonly "waveId": string
  readonly "wavePlanRef": string
}

export type WaveBarrierSatisfiedPayload = {
  readonly "waveId": string
  readonly "acceptedTaskIds": readonly string[]
  readonly "integrationReceiptRefs": readonly string[]
  readonly "specsCommitRef": string
}

export type TaskCreatedPayload = {
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "taskOrderRef": string
}

export type TaskLeasedPayload = {
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "agent": AgentIdentity
  readonly "workspaceLeaseId": string
  readonly "leaseExpiresAt": IsoDateTime
}

export type TaskCandidateSubmittedPayload = {
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "candidateId": string
  readonly "candidateRef": string
}

export type TaskBlockerSubmittedPayload = {
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "blockerId": string
  readonly "requestId"?: string
  readonly "evidenceRefs": readonly string[]
}

export type VerificationCompletedPayload = {
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "candidateId": string
  readonly "verificationReceiptRef": string
  readonly "disposition": "ACCEPTED" | "REWORK" | "BLOCKED" | "FROZEN" | "STRATEGIC" | "HUMAN_REVIEW_REQUIRED"
}

export type TaskAcceptedPayload = {
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "candidateId": string
  readonly "verificationReceiptRef": string
  readonly "integrationRequired": boolean
}

export type TaskCancelledPayload = {
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "reasonCode": "USER_CANCELLED" | "PARENT_CANCELLED" | "STEP_BUDGET_EXHAUSTED" | "NO_PROGRESS_LIMIT" | "AGENT_ABORTED"
  readonly "cancelledAgentId": string
}

export type TaskReworkRequestedPayload = {
  readonly "taskId": string
  readonly "previousVersion": number
  readonly "newVersion": number
  readonly "reasonCodes": readonly string[]
}

export type TaskIntegrationQueuedPayload = {
  readonly "taskId": string
  readonly "candidatePatchId": string
  readonly "integrationOrderId": string
}

export type TaskIntegratedPayload = {
  readonly "taskId": string
  readonly "integrationReceiptId": string
  readonly "commit": string
  readonly "treeHash": string
}

export type WorkspaceLeaseAcquiredPayload = {
  readonly "workspaceLeaseId": string
  readonly "taskId": string
  readonly "agentId": string
  readonly "workspaceSnapshotId": string
  readonly "expiresAt": IsoDateTime
}

export type WorkspaceSnapshotCreatedPayload = {
  readonly "workspaceSnapshotId": string
  readonly "taskId": string
  readonly "gitHead": string
  readonly "treeHash": string
  readonly "dirtyStateHash": string
}

export type WorkspaceLeaseReleasedPayload = {
  readonly "workspaceLeaseId": string
  readonly "taskId": string
  readonly "state": "RELEASED" | "EXPIRED" | "REVOKED"
  readonly "cleanupReceiptRef"?: string
}

export type WorkspaceDriftDetectedPayload = {
  readonly "workspaceSnapshotId": string
  readonly "expectedHead": string
  readonly "actualHead": string
  readonly "changedPaths": readonly string[]
  readonly "sourceSessionId"?: string
}

export type IntegrationConflictDetectedPayload = {
  readonly "integrationOrderId": string
  readonly "conflictReportRef": string
  readonly "affectedPaths": readonly string[]
}

export type IntegrationRegressionFailedPayload = {
  readonly "integrationOrderId": string
  readonly "checkReceiptRefs": readonly string[]
  readonly "failureArtifact": ArtifactRef
}

export type RadioRequestedPayload = {
  readonly "requestId": string
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "requestRef": string
}

export type RadioGuidanceIssuedPayload = {
  readonly "guidanceId": string
  readonly "requestId": string
  readonly "advisorId": string
  readonly "skillRefs": readonly TacticalSkillRef[]
}

export type RadioGuidanceDeliveredPayload = {
  readonly "guidanceId": string
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "deliveryReceiptRef": string
}

export type DecisionQuestionSetCreatedPayload = {
  readonly "decisionSetId": string
  readonly "originAgentId": string
  readonly "questionSetRef": string
  readonly "taskVersion"?: number
}

export type DecisionQuestionPresentedPayload = {
  readonly "decisionSetId": string
  readonly "presentationId": string
  readonly "rootSessionId": string
}

export type DecisionAnsweredPayload = {
  readonly "decisionSetId": string
  readonly "answerReceiptRef": string
  readonly "answeredBy": string
}

export type DecisionStalePayload = {
  readonly "decisionSetId": string
  readonly "reasonCode": "TASK_VERSION_CHANGED" | "MISSION_CHANGED" | "SOURCE_REVOKED" | "SUPERSEDED"
  readonly "taskVersion"?: number
}

export type DecisionExpiredPayload = {
  readonly "decisionSetId": string
  readonly "reason": "TTL" | "TASK_VERSION_CHANGED" | "MISSION_CANCELLED" | "SUPERSEDED" | "ORIGIN_AGENT_GONE"
}

export type OversightFrozenPayload = {
  readonly "targetAgentId": string
  readonly "taskId": string
  readonly "inspectionReportRef": string
  readonly "reasonCodes": readonly string[]
}

export type OversightReleasedPayload = {
  readonly "targetAgentId": string
  readonly "correctionOrderRef": string
  readonly "releasedBy": string
}

export type SpecsCommitRecordedPayload = {
  readonly "taskId": string
  readonly "commit": string
  readonly "treeHash": string
  readonly "changedPaths": readonly string[]
}

export type ContextCompactionRequiredPayload = {
  readonly "agentId": string
  readonly "compactionAttemptId": string
  readonly "meterTokens": number
  readonly "thresholdTokens": number
}

export type ContextCompactionAttemptedPayload = {
  readonly "attemptId": string
  readonly "agentId": string
  readonly "trigger": "PRESSURE" | "CONTEXT_OVERFLOW" | "MANUAL" | "HANDOFF"
  readonly "provider": string
  readonly "model": string
}

export type ContextCompactionCompletedPayload = {
  readonly "attemptId": string
  readonly "outcome": "SUCCEEDED" | "NO_SAFE_RANGE" | "FAILED" | "CANCELLED"
  readonly "summaryEventSeq"?: number
  readonly "errorCode"?: string
}

export type ModelSelectionChangedPayload = {
  readonly "sessionId": string
  readonly "provider": string
  readonly "model": string
  readonly "source": "PRESET_DEFAULT" | "NEW_SESSION_SELECTION" | "SESSION_MODEL_SELECTOR" | "RESUME"
  readonly "previousProvider"?: string
  readonly "previousModel"?: string
}

export type ModelSelectionRejectedPayload = {
  readonly "provider": string
  readonly "model": string
  readonly "reasonCode": "UNSUPPORTED_REASONING" | "CONTEXT_TOO_SMALL" | "DATA_RESIDENCY" | "TOOL_CALLING" | "BUDGET" | "UNSUPPORTED_PROVIDER"
  readonly "previousReceiptRef": string
}

export type ModelFallbackPayload = {
  readonly "agentId": string
  readonly "fromProvider": string
  readonly "fromModel": string
  readonly "toProvider": string
  readonly "toModel": string
  readonly "reason": string
}

export type BudgetReservedPayload = {
  readonly "reservationId": string
  readonly "policyId": string
  readonly "scope": "MISSION" | "DIRECTION" | "WAVE" | "TASK" | "OPERATION"
  readonly "reserved": {
    readonly "modelRequests"?: number
    readonly "reasoningTokens"?: number
    readonly "toolCalls"?: number
    readonly "apiCalls"?: number
    readonly "wallClockSeconds"?: number
    readonly "storageBytes"?: number
  }
  readonly "leaseUntil"?: IsoDateTime
}

export type BudgetSettledPayload = {
  readonly "reservationId": string
  readonly "usageReceiptId": string
  readonly "actual": {
    readonly "modelRequests"?: number
    readonly "reasoningTokens"?: number
    readonly "toolCalls"?: number
    readonly "apiCalls"?: number
    readonly "wallClockSeconds"?: number
    readonly "storageBytes"?: number
  }
  readonly "released"?: {
    readonly "modelRequests"?: number
    readonly "reasoningTokens"?: number
    readonly "toolCalls"?: number
    readonly "apiCalls"?: number
    readonly "wallClockSeconds"?: number
    readonly "storageBytes"?: number
  }
}

export type BudgetThresholdReachedPayload = {
  readonly "budgetScope": "DEPLOYMENT" | "TENANT" | "MISSION" | "WAVE" | "TASK"
  readonly "budgetKind": "MODEL_REQUESTS" | "REASONING_TOKENS" | "WALL_CLOCK" | "TOOL_CALLS" | "API_CALLS" | "CONCURRENT_AGENTS" | "RADIO_ROUNDS" | "REWORK_ATTEMPTS" | "STORAGE_BYTES"
  readonly "used": number
  readonly "limit": number
  readonly "disposition": "PAUSE_AND_REPORT" | "REQUIRE_USER_AUTHORIZATION" | "DEGRADE_NONCRITICAL_RESEARCH" | "CANCEL_SPECULATIVE_TASKS"
}

export type BudgetExhaustedPayload = {
  readonly "policyId": string
  readonly "scope": "DEPLOYMENT" | "TENANT" | "MISSION" | "DIRECTION" | "WAVE" | "TASK"
  readonly "disposition": "PAUSE_AND_REPORT" | "REQUIRE_USER_AUTHORIZATION" | "DEGRADE_NONCRITICAL_RESEARCH" | "CANCEL_SPECULATIVE_TASKS" | "TERMINATE_TASK" | "TERMINATE_MISSION"
  readonly "usedPercent": number
}

export type MemoryTrajectoryCreatedPayload = {
  readonly "waveId": string
  readonly "memoryRef": string
  readonly "sourceEventCount": number
}

export type MemoryEffectivenessScheduledPayload = {
  readonly "compactionId": string
  readonly "evaluationJobId": string
}

export type MemoryEffectivenessCreatedPayload = {
  readonly "compactionId": string
  readonly "assessmentRef": string
  readonly "causalStrength": "none" | "correlated" | "incremental" | "causal-supported"
}

export type TacticVersionPublishedPayload = {
  readonly "skillId": string
  readonly "version": unknown
  readonly "lifecycle": "DRAFT" | "SIMULATION" | "CANARY" | "TESTING" | "STABLE" | "QUARANTINED" | "DEPRECATED" | "RETIRED"
}

export type AgentTemplateInstantiatedPayload = {
  readonly "templateId": string
  readonly "revision": number
  readonly "agentId": string
  readonly "provider": string
  readonly "model": string
  readonly "reasoningEffort": ReasoningEffort
}

export type AgentExecutionBoundPayload = {
  readonly "bindingId": string
  readonly "agentId": string
  readonly "agentGeneration": number
  readonly "templateId": string
  readonly "templateRevision": number
  readonly "provider": string
  readonly "model": string
  readonly "reasoningEffort": "low" | "high" | "max"
  readonly "presetGeneration": string
}

export type BrainstormStartedPayload = {
  readonly "orderId": string
  readonly "rootSessionId": string
  readonly "projectStage": "IDEATION" | "SPECS_ONLY" | "ACTIVE" | "LEGACY"
}

export type BrainstormDecisionRecordedPayload = {
  readonly "orderId": string
  readonly "decisionId": string
  readonly "answerReceiptRef": string
}

export type BrainstormCompletedPayload = {
  readonly "orderId": string
  readonly "missionIntentRef": string
  readonly "specsMaintenanceOrderRef"?: string
}

export type StaffChiefAdviceIssuedPayload = {
  readonly "adviceId": string
  readonly "decisionId": string
  readonly "adviceRef": string
  readonly "confidence": number
}

export type MissionCompletedPayload = {
  readonly "completionReportRef": string
  readonly "acceptedTaskCount": number
  readonly "integratedTaskCount": number
}

export type MissionCancelledPayload = {
  readonly "reason": string
  readonly "authorizedBy": string
  readonly "cancellationReceiptRef": string
}

export type TagChangedPayload = {
  readonly "tagId": string
  readonly "revision": number
  readonly "operation": "created" | "renamed" | "paused" | "resumed" | "deleted"
}

export type AgentTemplateChangedPayload = {
  readonly "templateId": string
  readonly "revision": number
  readonly "operation": "created" | "activated" | "paused" | "retired"
}

export type ToolProfileChangedPayload = {
  readonly "toolProfileId": string
  readonly "revision": number
  readonly "operation": "created" | "activated" | "paused" | "retired"
}

export type PermissionProfileChangedPayload = {
  readonly "permissionProfileId": string
  readonly "revision": number
  readonly "operation": "created" | "activated" | "revoked" | "retired"
}

export type ApiGrantChangedPayload = {
  readonly "grantId": string
  readonly "revision": number
  readonly "operation": "created" | "activated" | "revoked" | "expired"
}

export type ModelCapabilityChangedPayload = {
  readonly "profileId": string
  readonly "revision": number
  readonly "provider": string
  readonly "model": string
  readonly "operation": "created" | "validated" | "deprecated"
}

export type ContextManifestCreatedPayload = {
  readonly "manifestId": string
  readonly "missionId": string
  readonly "taskId": string
  readonly "taskVersion": number
  readonly "missionRevision": number
  readonly "agentId": string
  readonly "agentGeneration": number
  readonly "sessionId": string
  readonly "turn": number
  readonly "step": number
  readonly "artifactRef": ArtifactRef
  readonly "manifestSha256": string
  readonly "sectionKinds": readonly ("CONSTITUTION" | "STATE" | "EVIDENCE" | "WORKING")[]
  readonly "omittedEvidenceCount": number
  readonly "tokenBudget": number
}

export type DataResidencyPolicyChangedPayload = {
  readonly "policyId": string
  readonly "revision": number
  readonly "status": "DRAFT" | "ACTIVE" | "PAUSED" | "REVOKED" | "RETIRED"
}

export type RedactionPolicyChangedPayload = {
  readonly "policyId": string
  readonly "revision": number
  readonly "status": "DRAFT" | "ACTIVE" | "PAUSED" | "REVOKED" | "RETIRED"
}

export type VerifierProfileChangedPayload = {
  readonly "verifierProfileId": string
  readonly "revision": number
  readonly "status": "DRAFT" | "ACTIVE" | "PAUSED" | "REVOKED" | "RETIRED"
}

export type ResourceBudgetPolicyChangedPayload = {
  readonly "policyId": string
  readonly "revision": number
  readonly "status": "DRAFT" | "ACTIVE" | "PAUSED" | "REVOKED" | "RETIRED"
}

export type AuthorizationGrantedPayload = {
  readonly "authorizationId": string
  readonly "principalId": string
  readonly "scope": string
  readonly "expiresAt": IsoDateTime
}

export type AuthorizationRevokedPayload = {
  readonly "authorizationId": string
  readonly "principalId": string
  readonly "reason": string
}

export type TacticalIngestionRequestedPayload = {
  readonly "requestId": string
  readonly "sourceKind": "SESSION_RANGE" | "DIRECT_TEXT" | "ARTIFACT"
  readonly "requestedTagIds": readonly string[]
}

export type TacticalIngestionSourceSnapshottedPayload = {
  readonly "requestId": string
  readonly "snapshotId": string
  readonly "sourceHash": string
  readonly "classification": DataClassification
}

export type TacticalIngestionCandidateCreatedPayload = {
  readonly "requestId": string
  readonly "candidateId": string
  readonly "candidateHash": string
  readonly "operation": "NEW_TACTIC" | "SUPPLEMENT"
}

export type TacticalIngestionReviewedPayload = {
  readonly "requestId": string
  readonly "candidateId": string
  readonly "disposition": "APPROVED_AS_DRAFT" | "RETURNED" | "REJECTED"
  readonly "reviewerId": string
}

export type TacticalSourceRevokedPayload = {
  readonly "snapshotId": string
  readonly "reason": "OWNER_REQUEST" | "LICENSE_CHANGE" | "SECURITY_INCIDENT" | "PROVEN_INCORRECT" | "RETENTION_EXPIRY"
  readonly "revocationOrderId": string
}

export type TacticalSourceImpactAssessedPayload = {
  readonly "revocationOrderId": string
  readonly "impactReportRef": string
  readonly "affectedTacticVersions": readonly string[]
  readonly "affectedTaskCount": number
}

export type TacticalSourceRevalidationCompletedPayload = {
  readonly "revocationOrderId": string
  readonly "disposition": "CLEARED" | "PARTIALLY_CLEARED" | "REMAINS_QUARANTINED"
  readonly "reverifiedTaskIds": readonly string[]
  readonly "reportRef"?: string
}

export type PerformanceEvaluationRequestedPayload = {
  readonly "evaluationRequestId": string
  readonly "datasetJobId": string
  readonly "requestedBy": string
}

export type PerformanceEvaluationDatasetFrozenPayload = {
  readonly "evaluationRequestId": string
  readonly "datasetHash": string
  readonly "datasetArtifact": ArtifactRef
}

export type PerformanceEvaluationTemplateCompletedPayload = {
  readonly "evaluationRequestId": string
  readonly "templateId": string
  readonly "templateRevision": number
  readonly "performanceArtifact": ArtifactRef
}

export type PerformanceEvaluationCompletedPayload = {
  readonly "evaluationRequestId": string
  readonly "reportId": string
  readonly "reportArtifact": ArtifactRef
}

export type PerformanceEvaluationCancelledPayload = {
  readonly "evaluationRequestId": string
  readonly "reasonCode": "USER_CANCELLED" | "BUDGET_EXHAUSTED" | "AUTHORIZATION_REVOKED" | "DATASET_INVALID" | "BUNDLE_DISABLED"
  readonly "partialDatasetManifestRef"?: string
}

export type PerformanceEvaluationReopenedPayload = {
  readonly "evaluationRequestId": string
  readonly "previousReportId": string
  readonly "reason": string
  readonly "appealRef": string
}

export type PerformanceEvaluationAppealResolvedPayload = {
  readonly "appealId": string
  readonly "disposition": "UPHELD" | "PARTIALLY_UPHELD" | "DENIED"
  readonly "resolvedBy": string
  readonly "supersedingReportId"?: string
}

export type PerformanceEvaluationAppealSubmittedPayload = {
  readonly "appealId": string
  readonly "reportId": string
  readonly "reportRevision": number
  readonly "submittedBy": string
  readonly "grounds": "DATASET_ERROR" | "RUBRIC_ERROR" | "ATTRIBUTION_ERROR" | "MISSING_CONTEXT" | "OTHER"
}

export type PresetGenerationInstalledPayload = {
  readonly "presetId": "military"
  readonly "generation": string
  readonly "manifestHash": string
  readonly "compatibility": "RC2_CURRENT" | "RC2_ARCHIVED"
}

export type PresetGenerationDeprecatedPayload = {
  readonly "presetId": "military"
  readonly "generation": string
  readonly "replacementGeneration": string
}

export type CompatibilityProbedPayload = {
  readonly "reportId": string
  readonly "dshCommit": string
  readonly "disposition": "READY" | "DEGRADED_READ_ONLY" | "MIGRATION_REQUIRED" | "UNSUPPORTED"
}

export type BundleInstalledPayload = {
  readonly "operationId": string
  readonly "bundleVersion": string
  readonly "receiptRef": string
}

export type BundleUpgradedPayload = {
  readonly "operationId": string
  readonly "fromVersion": string
  readonly "toVersion": string
  readonly "receiptRef": string
}

export type BundleRolledBackPayload = {
  readonly "operationId": string
  readonly "fromVersion": string
  readonly "toVersion": string
  readonly "receiptRef": string
}

export type BundleDisabledPayload = {
  readonly "operationId": string
  readonly "receiptRef": string
  readonly "existingSessionDisposition"?: "ALLOW_CONVERGENCE" | "READ_ONLY" | "PAUSE"
}

export type BundleUninstalledPayload = {
  readonly "operationId": string
  readonly "bundleVersion": string
  readonly "dataDisposition": "RETAINED" | "EXPORTED_AND_REMOVED" | "REMOVED"
  readonly "receiptRef": string
}

export interface MissionEventPayloadMap {
  readonly "military/session-bound": MilitarySessionBoundPayload
  readonly "military/session-quarantined": MilitarySessionQuarantinedPayload
  readonly "preset/generation-resume-checked": PresetGenerationResumeCheckedPayload
  readonly "preset/migration-completed": PresetMigrationCompletedPayload
  readonly "mission/started": MissionStartedPayload
  readonly "mission/command-accepted": MissionCommandAcceptedPayload
  readonly "mission/intent-ratified": MissionIntentRatifiedPayload
  readonly "direction/ratified": DirectionRatifiedPayload
  readonly "wave/opened": WaveOpenedPayload
  readonly "wave/barrier-satisfied": WaveBarrierSatisfiedPayload
  readonly "task/created": TaskCreatedPayload
  readonly "task/leased": TaskLeasedPayload
  readonly "task/candidate-submitted": TaskCandidateSubmittedPayload
  readonly "task/blocker-submitted": TaskBlockerSubmittedPayload
  readonly "verification/completed": VerificationCompletedPayload
  readonly "task/accepted": TaskAcceptedPayload
  readonly "task/cancelled": TaskCancelledPayload
  readonly "task/rework-requested": TaskReworkRequestedPayload
  readonly "task/integration-queued": TaskIntegrationQueuedPayload
  readonly "task/integrated": TaskIntegratedPayload
  readonly "workspace/lease-acquired": WorkspaceLeaseAcquiredPayload
  readonly "workspace/snapshot-created": WorkspaceSnapshotCreatedPayload
  readonly "workspace/lease-released": WorkspaceLeaseReleasedPayload
  readonly "workspace/drift-detected": WorkspaceDriftDetectedPayload
  readonly "integration/conflict-detected": IntegrationConflictDetectedPayload
  readonly "integration/regression-failed": IntegrationRegressionFailedPayload
  readonly "radio/requested": RadioRequestedPayload
  readonly "radio/guidance-issued": RadioGuidanceIssuedPayload
  readonly "radio/guidance-delivered": RadioGuidanceDeliveredPayload
  readonly "decision/question-set-created": DecisionQuestionSetCreatedPayload
  readonly "decision/question-presented": DecisionQuestionPresentedPayload
  readonly "decision/answered": DecisionAnsweredPayload
  readonly "decision/stale": DecisionStalePayload
  readonly "decision/expired": DecisionExpiredPayload
  readonly "oversight/frozen": OversightFrozenPayload
  readonly "oversight/released": OversightReleasedPayload
  readonly "specs/commit-recorded": SpecsCommitRecordedPayload
  readonly "context/compaction-required": ContextCompactionRequiredPayload
  readonly "context/compaction-attempted": ContextCompactionAttemptedPayload
  readonly "context/compaction-completed": ContextCompactionCompletedPayload
  readonly "model/selection-changed": ModelSelectionChangedPayload
  readonly "model/selection-rejected": ModelSelectionRejectedPayload
  readonly "model/fallback": ModelFallbackPayload
  readonly "budget/reserved": BudgetReservedPayload
  readonly "budget/settled": BudgetSettledPayload
  readonly "budget/threshold-reached": BudgetThresholdReachedPayload
  readonly "budget/exhausted": BudgetExhaustedPayload
  readonly "memory/trajectory-created": MemoryTrajectoryCreatedPayload
  readonly "memory/effectiveness-scheduled": MemoryEffectivenessScheduledPayload
  readonly "memory/effectiveness-created": MemoryEffectivenessCreatedPayload
  readonly "tactic/version-published": TacticVersionPublishedPayload
  readonly "agent-template/instantiated": AgentTemplateInstantiatedPayload
  readonly "agent/execution-bound": AgentExecutionBoundPayload
  readonly "brainstorm/started": BrainstormStartedPayload
  readonly "brainstorm/decision-recorded": BrainstormDecisionRecordedPayload
  readonly "brainstorm/completed": BrainstormCompletedPayload
  readonly "staff/chief-advice-issued": StaffChiefAdviceIssuedPayload
  readonly "mission/completed": MissionCompletedPayload
  readonly "mission/cancelled": MissionCancelledPayload
}

export interface AdministrativeEventPayloadMap {
  readonly "tag/changed": TagChangedPayload
  readonly "agent-template/changed": AgentTemplateChangedPayload
  readonly "tool-profile/changed": ToolProfileChangedPayload
  readonly "permission-profile/changed": PermissionProfileChangedPayload
  readonly "api-grant/changed": ApiGrantChangedPayload
  readonly "model-capability/changed": ModelCapabilityChangedPayload
  readonly "context/manifest-created": ContextManifestCreatedPayload
  readonly "data-residency-policy/changed": DataResidencyPolicyChangedPayload
  readonly "redaction-policy/changed": RedactionPolicyChangedPayload
  readonly "verifier-profile/changed": VerifierProfileChangedPayload
  readonly "resource-budget-policy/changed": ResourceBudgetPolicyChangedPayload
  readonly "authorization/granted": AuthorizationGrantedPayload
  readonly "authorization/revoked": AuthorizationRevokedPayload
  readonly "tactical-ingestion/requested": TacticalIngestionRequestedPayload
  readonly "tactical-ingestion/source-snapshotted": TacticalIngestionSourceSnapshottedPayload
  readonly "tactical-ingestion/candidate-created": TacticalIngestionCandidateCreatedPayload
  readonly "tactical-ingestion/reviewed": TacticalIngestionReviewedPayload
  readonly "tactical-source/revoked": TacticalSourceRevokedPayload
  readonly "tactical-source/impact-assessed": TacticalSourceImpactAssessedPayload
  readonly "tactical-source/revalidation-completed": TacticalSourceRevalidationCompletedPayload
  readonly "performance-evaluation/requested": PerformanceEvaluationRequestedPayload
  readonly "performance-evaluation/dataset-frozen": PerformanceEvaluationDatasetFrozenPayload
  readonly "performance-evaluation/template-completed": PerformanceEvaluationTemplateCompletedPayload
  readonly "performance-evaluation/completed": PerformanceEvaluationCompletedPayload
  readonly "performance-evaluation/cancelled": PerformanceEvaluationCancelledPayload
  readonly "performance-evaluation/reopened": PerformanceEvaluationReopenedPayload
  readonly "performance-evaluation/appeal-resolved": PerformanceEvaluationAppealResolvedPayload
  readonly "performance-evaluation/appeal-submitted": PerformanceEvaluationAppealSubmittedPayload
  readonly "preset-generation/installed": PresetGenerationInstalledPayload
  readonly "preset-generation/deprecated": PresetGenerationDeprecatedPayload
  readonly "compatibility/probed": CompatibilityProbedPayload
  readonly "bundle/installed": BundleInstalledPayload
  readonly "bundle/upgraded": BundleUpgradedPayload
  readonly "bundle/rolled-back": BundleRolledBackPayload
  readonly "bundle/disabled": BundleDisabledPayload
  readonly "bundle/uninstalled": BundleUninstalledPayload
}

export interface MissionEventEnvelope<K extends keyof MissionEventPayloadMap> {
  readonly schemaVersion: '2.0.0'
  readonly eventId: string
  readonly missionId: string
  readonly seq: number
  readonly aggregateRevision: number
  readonly type: K
  readonly timestamp: IsoDateTime
  readonly actor: AgentIdentity
  readonly causationId?: string
  readonly correlationId?: string
  readonly idempotencyKey?: string
  readonly payload: MissionEventPayloadMap[K]
}

export interface AdministrativeEventEnvelope<K extends keyof AdministrativeEventPayloadMap> {
  readonly schemaVersion: '2.0.0'
  readonly eventId: string
  readonly seq: number
  readonly aggregateRevision: number
  readonly type: K
  readonly timestamp: IsoDateTime
  readonly actorId: string
  readonly tenantId: string
  readonly causationId?: string
  readonly correlationId?: string
  readonly idempotencyKey?: string
  readonly payload: AdministrativeEventPayloadMap[K]
}

export type MissionEvent = {
  [K in keyof MissionEventPayloadMap]: MissionEventEnvelope<K>
}[keyof MissionEventPayloadMap]

export type MilitaryAdministrativeEvent = {
  [K in keyof AdministrativeEventPayloadMap]: AdministrativeEventEnvelope<K>
}[keyof AdministrativeEventPayloadMap]

export const missionEventTypes = [
  "military/session-bound",
  "military/session-quarantined",
  "preset/generation-resume-checked",
  "preset/migration-completed",
  "mission/started",
  "mission/command-accepted",
  "mission/intent-ratified",
  "direction/ratified",
  "wave/opened",
  "wave/barrier-satisfied",
  "task/created",
  "task/leased",
  "task/candidate-submitted",
  "task/blocker-submitted",
  "verification/completed",
  "task/accepted",
  "task/cancelled",
  "task/rework-requested",
  "task/integration-queued",
  "task/integrated",
  "workspace/lease-acquired",
  "workspace/snapshot-created",
  "workspace/lease-released",
  "workspace/drift-detected",
  "integration/conflict-detected",
  "integration/regression-failed",
  "radio/requested",
  "radio/guidance-issued",
  "radio/guidance-delivered",
  "decision/question-set-created",
  "decision/question-presented",
  "decision/answered",
  "decision/stale",
  "decision/expired",
  "oversight/frozen",
  "oversight/released",
  "specs/commit-recorded",
  "context/compaction-required",
  "context/compaction-attempted",
  "context/compaction-completed",
  "model/selection-changed",
  "model/selection-rejected",
  "model/fallback",
  "budget/reserved",
  "budget/settled",
  "budget/threshold-reached",
  "budget/exhausted",
  "memory/trajectory-created",
  "memory/effectiveness-scheduled",
  "memory/effectiveness-created",
  "tactic/version-published",
  "agent-template/instantiated",
  "agent/execution-bound",
  "brainstorm/started",
  "brainstorm/decision-recorded",
  "brainstorm/completed",
  "staff/chief-advice-issued",
  "mission/completed",
  "mission/cancelled",
] as const
export type MissionEventType = typeof missionEventTypes[number]

export const administrativeEventTypes = [
  "tag/changed",
  "agent-template/changed",
  "tool-profile/changed",
  "permission-profile/changed",
  "api-grant/changed",
  "model-capability/changed",
  "context/manifest-created",
  "data-residency-policy/changed",
  "redaction-policy/changed",
  "verifier-profile/changed",
  "resource-budget-policy/changed",
  "authorization/granted",
  "authorization/revoked",
  "tactical-ingestion/requested",
  "tactical-ingestion/source-snapshotted",
  "tactical-ingestion/candidate-created",
  "tactical-ingestion/reviewed",
  "tactical-source/revoked",
  "tactical-source/impact-assessed",
  "tactical-source/revalidation-completed",
  "performance-evaluation/requested",
  "performance-evaluation/dataset-frozen",
  "performance-evaluation/template-completed",
  "performance-evaluation/completed",
  "performance-evaluation/cancelled",
  "performance-evaluation/reopened",
  "performance-evaluation/appeal-resolved",
  "performance-evaluation/appeal-submitted",
  "preset-generation/installed",
  "preset-generation/deprecated",
  "compatibility/probed",
  "bundle/installed",
  "bundle/upgraded",
  "bundle/rolled-back",
  "bundle/disabled",
  "bundle/uninstalled",
] as const
export type AdministrativeEventType = typeof administrativeEventTypes[number]
